### ISSUE TITLE
TypeError: Fetch argument None has invalid type <class 'NoneType'>

### ISSUE THREAD

**Issue by marleymwangi** [RobRomijnders/LSTM_tsc#10]
Hi, first thing: your project is very interesting. 
Second: I got an error at the execution at 

summary = sess.run( merged , {input_data: nextBatch, labels: nextBatchLabels})

Do you have any ideas how to fix it ?

Thank you in advance

Traceback (most recent call last):
  File "Oriole+LSTM.py", line 220, in <module>
    summary = sess.run( merged , {input_data: nextBatch, labels: nextBatchLabels})
  File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
    run_metadata_ptr)
  File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 984, in _run
    self._graph, fetches, feed_dict_string, feed_handles=feed_handles)
  File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 410, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 227, in for_fetch
    (fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>

**Comment by RobRomijnders** [comment]
I see you closed it? So it is fixed?
